version: 0.1
phases:
  install:
    runtime-versions:
        python: 3.8
    commands:
      - sam package --template-file samTemplate.yaml --s3-bucket pdomala-lambda-pipeline --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
     - outputSamTemplate.yaml
